"""The Alembic history builds the schema and matches the models exactly."""

from pathlib import Path

import pytest
from alembic.util.exc import AutogenerateDiffsDetected
from flask_migrate import check, downgrade, upgrade
from sqlalchemy import inspect

from agrisense import create_app
from agrisense.extensions import db

MIGRATIONS = str(Path(__file__).resolve().parent.parent / "migrations")
TABLES = {"app_user", "login_attempt", "farm", "plot", "soil_card", "event", "cached_price", "cached_weather"}


@pytest.fixture
def migrated_app(tmp_path):
    app = create_app("testing", {"SQLALCHEMY_DATABASE_URI": f"sqlite:///{tmp_path / 'm.db'}"})
    with app.app_context():
        upgrade(directory=MIGRATIONS)
        yield app
        db.session.remove()


def test_upgrade_creates_all_adr003_tables(migrated_app):
    assert TABLES <= set(inspect(db.engine).get_table_names())


def test_models_and_migrations_agree(migrated_app):
    try:
        check(directory=MIGRATIONS)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure message
        pytest.fail(f"Models changed without a migration: {exc}")


def test_downgrade_to_empty(migrated_app):
    downgrade(directory=MIGRATIONS, revision="base")
    assert not TABLES & set(inspect(db.engine).get_table_names())
