"""initial schema

Revision ID: b2b2a4d9e67e
Revises: 
Create Date: 2026-10-08 05:01:10.242860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b2a4d9e67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hmac', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pin_reset_required', sa.Boolean(), nullable=False),
    sa.Column('pin_reset_code_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pin_reset_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pin_reset_by_id'], ['app_user.id'], name=op.f('fk_app_user_pin_reset_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('phone_hmac', name=op.f('uq_app_user_phone_hmac'))
    )
    op.create_table('cached_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('district', sa.String(length=60), nullable=False),
    sa.Column('market', sa.String(length=80), nullable=False),
    sa.Column('commodity', sa.String(length=80), nullable=False),
    sa.Column('variety', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cached_price')),
    sa.UniqueConstraint('source', 'market', 'commodity', 'variety', 'grade', 'arrival_date', name='uq_cached_price_row')
    )
    with op.batch_alter_table('cached_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_price_arrival_date'), ['arrival_date'], unique=False)

    op.create_table('cached_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('lat_r', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lon_r', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cached_weather')),
    sa.UniqueConstraint('source', 'lat_r', 'lon_r', name='uq_cached_weather_cell')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('phone_hmac', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt'))
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_phone_hmac'), ['phone_hmac'], unique=False)

    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('district_code', sa.String(length=16), nullable=True),
    sa.Column('lat', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('lon', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_farm_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm'))
    )
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_user_id'), ['user_id'], unique=False)

    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('area_input_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('area_input_unit', sa.String(length=16), nullable=True),
    sa.Column('irrigation_source', sa.String(length=16), nullable=True),
    sa.Column('current_crop', sa.String(length=32), nullable=True),
    sa.Column('season', sa.String(length=8), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_plot_farm_id_farm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot'))
    )
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_farm_id'), ['farm_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_event_plot_id_plot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_plot_kind_time', ['plot_id', 'kind', 'occurred_at'], unique=False)

    op.create_table('soil_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('sampled_on', sa.Date(), nullable=True),
    sa.Column('n_kg_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('p_kg_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('k_kg_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('oc_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ec_ds_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_soil_card_plot_id_plot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soil_card'))
    )
    with op.batch_alter_table('soil_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soil_card_plot_id'), ['plot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_card_plot_id'))

    op.drop_table('soil_card')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_plot_kind_time')

    op.drop_table('event')
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_farm_id'))

    op.drop_table('plot')
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_user_id'))

    op.drop_table('farm')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_phone_hmac'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_attempted_at'))

    op.drop_table('login_attempt')
    op.drop_table('cached_weather')
    with op.batch_alter_table('cached_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_price_arrival_date'))

    op.drop_table('cached_price')
    op.drop_table('app_user')
    # ### end Alembic commands ###
